AgenciaTurismo/AgenciaTurismo/Controllers/ClientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AgenciaTurismo.Models;

namespace AgenciaTurismo.Controllers
{
    public class ClientesController : Controller
    {
        private readonly BancoDados _context;

        public ClientesController(BancoDados context)
        {
            _context = context;
        }

        // GET: Clientes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Clientes.ToListAsync());
        }


        // GET: Clientes/Create
        public IActionResult AddEdit(int id = 0)
        {
            if (id == 0)
                return View(new Cliente());
            else
                return View(_context.Clientes.Find(id));
        }

        // POST: Clientes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddEdit([Bind("Id,Nome,Cpf")] Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                if (cliente.Id == 0)
                    _context.Add(cliente);
                else
                    _context.Update(cliente);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(cliente);
        }

  
        // GET: Clientes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            var cliente = await _context.Clientes.FindAsync(id);
            _context.Clientes.Remove(cliente);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

AgenciaTurismo/AgenciaTurismo/Controllers/ContatoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AgenciaTurismo.Models;

namespace AgenciaTurismo.Controllers
{
    public class ContatoesController : Controller
    {
        private readonly BancoDados _context;

        public ContatoesController(BancoDados context)
        {
            _context = context;
        }

        // GET: Contatoes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Contatos.ToListAsync());
        }


        // GET: Contatoes/Create
        public IActionResult AddEdit(int id=0)
        {
            if (id == 0)
                return View(new Contato());
            else
                return View(_context.Contatos.Find(id));
        }

        // POST: Contatoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddEdit([Bind("Id,Nome,Email")] Contato contato)
        {
            if (ModelState.IsValid)
            {
                if(contato.Id == 0)
                _context.Add(contato);
                else
                    _context.Update(contato);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(contato);
        }


        // GET: Contatoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            var contato = await _context.Contatos.FindAsync(id);
            _context.Contatos.Remove(contato);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

AgenciaTurismo/AgenciaTurismo/Controllers/DestinoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AgenciaTurismo.Models;

namespace AgenciaTurismo.Controllers
{
    public class DestinoesController : Controller
    {
        private readonly BancoDados _context;

        public DestinoesController(BancoDados context)
        {
            _context = context;
        }

        // GET: Destinoes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Destinos.ToListAsync());
        }

        // GET: Destinoes/Create
        public IActionResult AddEdit(int id= 0)
        {
            if (id == 0)
                return View(new Destino());
            else
                return View(_context.Destinos.Find(id));

        }

        // POST: Destinoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddEdit([Bind("Id,Nome,Valor,DataInicio,DataFinal,Descricao")] Destino destino)
        {
            if (ModelState.IsValid)
            {
                if (destino.Id == 0)
                    _context.Add(destino);
                else
                    _context.Update(destino);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(destino);
        }

        // GET: Destinoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            var destino = await _context.Destinos.FindAsync(id);
            _context.Destinos.Remove(destino);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

    }
}

AgenciaTurismo/AgenciaTurismo/Controllers/HomeController.cs
using AgenciaTurismo.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace AgenciaTurismo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AgenciaTurismo/AgenciaTurismo/Controllers/PromocaosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AgenciaTurismo.Models;

namespace AgenciaTurismo.Controllers
{
    public class PromocaosController : Controller
    {
        private readonly BancoDados _context;

        public PromocaosController(BancoDados context)
        {
            _context = context;
        }

        // GET: Promocaos
        public async Task<IActionResult> Index()
        {
            var bancoDados = _context.Promocaos.Include(p => p.Destino);
            return View(await bancoDados.ToListAsync());
        }

        // GET: Promocaos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var promocao = await _context.Promocaos
                .Include(p => p.Destino)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (promocao == null)
            {
                return NotFound();
            }

            return View(promocao);
        }

        // GET: Promocaos/Create
        public IActionResult AddEdit()
        {
            ViewData["DestinoId"] = new SelectList(_context.Destinos, "Id", "Nome");
            return View();
        }

        // POST: Promocaos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddEdit([Bind("Id,Desconto,DestinoId")] Promocao promocao)
        {
            if (ModelState.IsValid)
            {
                if (promocao.Id == 0)
                    _context.Add(promocao);
                else
                    _context.Update(promocao);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["DestinoId"] = new SelectList(_context.Destinos, "Id", "Nome", promocao.DestinoId);
            return View(promocao);
        }


        // GET: Promocaos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            var promocao = await _context.Promocaos.FindAsync(id);
            _context.Promocaos.Remove(promocao);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        
    }
}

AgenciaTurismo/AgenciaTurismo/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="https://scontent.frec38-1.fna.fbcdn.net/v/t1.18169-9/10600480_768195376560530_7213453269441602429_n.png?_nc_cat=102&ccb=1-5&_nc_sid=973b4a&_nc_ohc=n4MCho_kblIAX8PST9s&_nc_ht=scontent.frec38-1.fna&oh=00_AT91EPd4uqhuF-xPL7tv_fiZyruS2yHI0HoQLkg1DprykQ&oe=61DA7873" class="d-block w-100" alt="...">
    </div>
  </div>
</div>


<section class="card-container">

<div class="card cad">
  <img src="https://cdn-icons-png.flaticon.com/512/4760/4760483.png"  alt="...">
  <div class="card-body">
    <h5 class="card-title center">Contato</h5>
    <p class="card-text center">Selecionamos destidos incriveis para você, algumas com reservas flexíveis e outras a preços incríveis.</p>
    <a asp-controller="Contatoes" asp-action="AddEdit" class="btn btn-cad">Clique para conectar</a>
  </div>
</div>
<div class="card cad">
  <img src="https://cdn-icons-png.flaticon.com/512/4760/4760448.png" alt="...">
  <div class="card-body">
    <h5 class="card-title center">Cliente</h5>
    <p class="card-text center">Seja cliente e visite destidos incriveis, com reservas flexíveis e preços incríveis.</p>
    <a asp-controller="Clientes" asp-action="AddEdit" class="btn btn-cad">Clique para cadastrar</a>
  </div>
</div>
<div class="card cad">
  <img src="https://cdn-icons-png.flaticon.com/512/4760/4760440.png" alt="...">
  <div class="card-body">
    <h5 class="card-title center">Promoções</h5>
    <p class="card-text center">Selecionamos promoções incriveis para você, algumas com reservas flexíveis e outras a preços incríveis.</p>
    <a asp-controller="Promocaos" asp-action="AddEdit" class="btn btn-cad">Clique para cadastrar</a>
  </div>
</div>
<div class="card cad">
  <img src="https://cdn-icons-png.flaticon.com/512/4760/4760464.png" alt="...">
  <div class="card-body">
    <h5 class="card-title center">Destinos</h5>
    <p class="card-text center">Selecionamos destidos incriveis para você, algumas com reservas flexíveis e outras a preços incríveis.</p>
    <a asp-controller="Destinoes" asp-action="AddEdit" class="btn btn-cad">Clique para cadastrar</a>
  </div>
</div>
</section>

    <h1>“O que interessa na vida não é prever os perigos das viagens; é tê-las feito.”                 (Agostinho da Silva)</h1>

    <div class="card w-100 card-color">
  <div class="row">
    <div class="col-md-8 not">
      <img src="https://www.viagenscinematograficas.com.br/wp-content/uploads/2018/12/Fortaleza-O-que-Fazer-Melhores-Passeios-Capa-2.jpg" class="img-fluid rounded-start" alt="...">
    </div>
    <div class="col-md-4 card-color">
      <div class="card-body not-color">
        <h5 class="card-title">Por que viajar faz bem?</h5>
        <ol>
            <li>Viajar melhora o seu currículo</li> 
            <li>Viajar mantém seu coração saudável</li>
            <li>Viajar colabora para a sua felicidade</li>
            <li>Viajar amplia seu repertório</li>
            <li>Viajar te coloca em contato consigo mesmo</li>
            <li>Viajar te ajuda a lidar com o estresse</li>
            <li>Viajar te apresenta novas experiências culinárias</li>

        </ol>
      </div>
    </div>
  </div>
</div>